### ISSUE TITLE
Go Internal

### ISSUE THREAD

**Issue by Tautellini** [flipdeezy/SFSE_WeaponModelFOV#2]
First of all, nice job.

However, you are using a very complicated way of writing into the memory.
You are injecting a DLL by using the Script Extender. So you are doing an internal cheat already. You already have access to the process.

Instead of using WriteProcessMemory functions and trying to get the ProcessId first, you can just use the memcpy function to achieve the same thing.

It is used internally by the SFSE Common Lib when you use the safeWrite methods.
Feel free to have a look at: https://github.com/Tautellini/Starfield-WeaponFoV-SFSE-Plugin/blob/master/src/main.cpp

All you need to do is:

```
#include "sfse_common/Relocation.h"
#include "sfse_common/SafeWrite.h"

RelocAddr <uintptr_t*> weaponFoV = 0x79FD448;
safeWriteBuf(weaponFoV.getUIntPtr(), &newFoV, sizeof(float));

```

If you want, we may collaborate on this one, as I also plan to add functions to adjust the FoV for ADS Zoom and other things.

**Comment by flipdeezy** [comment]
That sounds great. I'm still learning my way around Script extender, gane hacking and C++. I'm mostly experimenting, and unsure of the best way to accomplish most things. Especially with no commonlib yet. I'm just doing what I can to get things working. 

Happy to collaborate on it and feel free to take whatever ive done and improve it, make it your own etc. I've credited you on the main page :)

**Comment by Tautellini** [comment]
I will still have to think about it. As I did go a different approach also in setting up the project. Im also not using VSCode but Visual Studio.

However, I feel like its not necessary to have the same solution two times, so I hided my upload on Nexusmods.

Appreciate it that you mentioned me on your Mod!

Do you plan on updating this mod regularily with new static adresses or pointers in case of Game Updates?
Because I could instead also just do a different Plugin just for ADS Zoom and other stuff, instead of both of us "competing". 



However, you should really update your approach. Its a good thing to learn how to use the WriteProcessMemory functions, this way you also already know how to do external hacking. But some of your users have problems with the name of the executable for example. All of those issues will vanish, if you just take advantage of being internal already. :)

**Comment by flipdeezy** [comment]
I understand take your time. 

Part of my thinking was trying to make it more resilient to updates since no Commonlib/Address library are available yet. Was trying to see if getting the base address dynamically would prevent some updating.

I will be trying to keep the mod updated best I can. I encourage you to unhide your mod and to add the FOV weapon model features. I think more choices are better for everyone! You already improved on my mod

Im going to look at updating my mod to use internal mem hook instead. I already did start converting some of the hooks as you saw. I'll credit you for sure though.

If u decide to work together on it let me know, otherwise I wish you nothing but success. I look forward to seeing more of your work!

**Comment by Tautellini** [comment]
Maybe I have some half-knowledge about those stuff, but the address for the weapon FoV is a static address. So would it even be possible to automatically scan for it in case of a game update?

The base address would be handled by the fact that you are already internal. As soon as your DLL is injected, you have the address. So this would be fixed already, as soon as the Script Extender updates.

I feel like, you just have to find the Offset again, and then update them every time a new update hits the road. But might be that im wrong about that.

**Comment by flipdeezy** [comment]
Oh yeah one thing to mention. 

whenever the player enters and exits dialogue, the model fov changes. Thats why I went with relatively short sleep timer. 100ms instead of 1000. Its noticeable when u exit dialogue at anything more than 100ms

I dodnt really want to use a thread. I re'd the memory address if the sub routine that writes to the View model address but it wasnt working reliably for me when not exiting dialogue

I tried best of both worlds solution to basically say when the player draws a weapon set the fov and then start the thread as a backup. Of course when the weapon is holstwrwd no need to take up cycles with a thread. 

Anyhow I hope you release your mod I thunk it will be awesome to have all those features in one mod.

**Comment by Tautellini** [comment]
Yeah I saw that, and I really liked that solution. It seems like a micro optimisation, but its still a much cleaner approach.

I feel like having a detached thread that would even update ever 100ms is not something that you really need to consider in terms of performance. If there are a lot of side effects that you need to handle, I would just ignore it to be honest.

**Comment by flipdeezy** [comment]
Yes youre exactly right, I was trying to prevent waiting for the script extender to update haha. Silly I know but its so early I wasnt sure how quickly things might be updated.  So I thought the offset might even remain the same, or worst case I jist RE the static pointer :)

Im much more comfortable using commonlib. Im a bit lost without it honestly

**Comment by Tautellini** [comment]
I feel like this is not possible the way the SFSE is handling the plugin loading at the moment, because you need to explicitely set the Runtime Version that the Plugin is compatible with. Lets say the game updates, the Script Extender would fail to load and therefore not inject your plugin at all, right?

**Comment by flipdeezy** [comment]
> Yeah I saw that, and I really liked that solution. It seems like a micro optimisation, but its still a much cleaner approach.
> 
> I feel like having a detached thread that would even update every 100ms is not something that you really need to consider in terms of performance. If there are a lot of side effects that you need to handle, I would just ignore it to be honest.

you know I went back and forth on tit for an hour with my beta tester. I couldn't decide if just running a single static thread and being careful to prevent race conditions was better than detaching the thread. I decided ultimately since I was going to go ahead and set the fov when the weapon was drawn (and that seemed to be the way that made it most invisible to the player) that I may as well detach the thread also.

**Comment by flipdeezy** [comment]
> I feel like this is not possible the way the SFSE is handling the plugin loading at the moment, because you need to explicitely set the Runtime Version that the Plugin is compatible with. Lets say the game updates, the Script Extender would fail to load and therefore not inject your plugin at all, right?

Actually yeah I think you're right and I'm an idiot lol

**Comment by Tautellini** [comment]
> > I feel like this is not possible the way the SFSE is handling the plugin loading at the moment, because you need to explicitely set the Runtime Version that the Plugin is compatible with. Lets say the game updates, the Script Extender would fail to load and therefore not inject your plugin at all, right?
> 
> Actually yeah I think you're right and I'm an idiot lol

Dont be too hard on yourself. Its a complicated topic. Its the first time I ever worked with the Script Extender and its basically just reading code, because there is no documentation at all. 

I initially also thought about going a kind of external approach to prevent any update measurements. But it just turned out, that this might not be worth it at all.

**Comment by flipdeezy** [comment]
Without library like Clib I am making it up as I go.  Good news is I heard the baseline version of CLib is almost ready and should be released in a few days. Should make things easier. Still no documentation but at least lots of Classes, implementation etc. is exposed

**Comment by flipdeezy** [comment]
already this is much better now. Thanks again

`#include "SFSE/Stub.h"
#include "RE.h"
#include "Settings.h"
#include "sfse_common/Relocation.h"
#include "sfse_common/SafeWrite.h"


static std::atomic<float> g_weaponFOV(110.0f); 
std::atomic<bool> shouldTerminateThread = false;
const RelocAddr<uintptr_t*> WeaponFOV_Offset = 0x79FD448;

void SetWeaponFOV(float fovValue) {
    safeWriteBuf(WeaponFOV_Offset.getUIntPtr(), &fovValue, sizeof(float));
}

// Temporary solution until I can find a better way to hook the FOV weapon model or a proper game update
void WeaponFOVMonitor() {
    while (!shouldTerminateThread) {
        float currentFOV = *reinterpret_cast<float*>(WeaponFOV_Offset.getUIntPtr());
        if (currentFOV != g_weaponFOV.load()) {
            SetWeaponFOV(g_weaponFOV.load());
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}

namespace Handler
{
    struct WeaponDraw
    {
        static bool thunk(RE::Actor* a_actor)
        {
            const auto result = func(a_actor);
            SetWeaponFOV(g_weaponFOV.load());
            return result;
        }
        static inline std::add_pointer_t<decltype(thunk)> func;
    };

    struct WeaponSheathe
    {
        static bool thunk(RE::Actor* a_actor)
        {
            const auto result = func(a_actor);
            SetWeaponFOV(g_weaponFOV.load());
            return result;
        }
        static inline std::add_pointer_t<decltype(thunk)> func;
    };

    void Install()
    {
        SFSE::AllocTrampoline(28);
        stl::write_thunk_call<WeaponDraw>(0x025F726C);
        stl::write_thunk_call<WeaponSheathe>(0x025F73A3);
        INFO("Hooked WeaponDraw and WeaponSheathe");
    }
}

namespace
{
    void MessageCallback(SFSE::MessagingInterface::Message* a_msg) noexcept
    {
        if (a_msg->type == SFSE::MessagingInterface::kPostLoad) {
            Handler::Install();
            Settings::GetSingleton()->LoadSettings();
            g_weaponFOV.store(Settings::GetSingleton()->weaponFOV);
        }
    }
}

DLLEXPORT constinit auto SFSEPlugin_Version = []() noexcept {
    SFSE::PluginVersionData data{};
    data.PluginVersion(Plugin::Version);
    data.PluginName(Plugin::NAME);
    data.AuthorName(Plugin::AUTHOR);
    data.UsesSigScanning(true);
    data.HasNoStructUse(true);
    data.CompatibleVersions({ RUNTIME_VERSION_1_7_23 });

    return data;
}();

DLLEXPORT bool SFSEAPI SFSEPlugin_Load(SFSEInterface* a_sfse)
{
    SFSE::Init(a_sfse);
    DKUtil::Logger::Init(Plugin::NAME, std::to_string(Plugin::Version));
    INFO("{} v{} loaded", Plugin::NAME, Plugin::Version);
    SFSE::GetMessagingInterface()->RegisterListener(MessageCallback);
    return true;
}`

**Comment by flipdeezy** [comment]
one last thing I've found after swapping to internal. It's much slower to check the current fov now. Maybe because we were checking form the hook before and now we are getting prioritized in a different way. It doesn't make sense because internal should be faster but it def seems slower, by a lot. It could also be my code. I'll work on it and let you know what I find
